### ISSUE TITLE
Documentation: Keybindings reference to Xresources

### ISSUE THREAD

**Issue by digital-tinta** [regolith-linux/website#132]
In the Keybindings page (https://regolith-linux.org/docs/getting-started/configuration/#keybindings) there is a link missing (1st paragraph, word "here", my highlight):

"The most common keybinding change is the super key. Regolith uses Xresources as the canonical source of truth for settings, which are read by various UI components. The table of Xresource keys open to user configuration can be found **_here_**. To change the default super binding from the windows key to alt, add the following line to the file ~/.config/regolith/Xresources:"

I believe the link should be: https://regolith-linux.org/docs/reference/xresources/

Hope it helps.

**Comment by moritzheiber** [comment]
Hey, thanks for pointing this out. This is fixed in the `v2` branch, which is due to be released any day.
