### ISSUE TITLE
Change Workspace Icons and Labels

### ISSUE THREAD

**Issue by chenvictor** [regolith-linux/website#138]
I'm trying to follow the docs here: https://regolith-linux.org/docs/howtos/change-workspace-icons/
to give workspaces textual descriptions, but the workspace tabs still only show the index.

I currently have
```
i3-wm.gaps.inner.size: 15
i3-wm.gaps.smart: on
i3-wm.bar.position: top

i3-wm.workspace.01.name: 1: General
i3-wm.workspace.02.name: 2: Chat
i3-wm.workspace.06.name: 6: Web
```

In my Xresources file and the gaps and bar position seem to be working.

Is this documentation up to date?

**Comment by moritzheiber** [comment]
What do you mean by "index"? Could you give us a better description of what you're trying to achieve?

**Comment by chenvictor** [comment]
By "index", I mean workspace number.

I managed to get it working now, but this is what I was going for:

![image](https://user-images.githubusercontent.com/32944695/110065684-92325980-7d24-11eb-89f3-de175028bf2a.png)

Where the workspace number and text is shown.

I'm not sure why but `regolith-look refresh` was not sufficient and I had to restart my computer to get the text to show up.
