### ISSUE TITLE
"Tells us how we can improve" link is dead

### ISSUE THREAD

**Issue by msoutopico** [regolith-linux/website#139]
### Steps to reproduce 

When you click on that link at the bottom of any page in the website (e.g. https://regolith-linux.org/docs/howtos/configure-wallpaper/), 

### Actual results 

the link points to https://github.com/regolith-linux/regolith-linux.github.io/issues/new, which doesn't exist.

### Expected results

I guess it should be pointing to https://github.com/regolith-linux/website/issues/new

**Comment by moritzheiber** [comment]
Thanks! That should be fixed now.
