### ISSUE TITLE
Document Lists destructive echo command.

### ISSUE THREAD

**Issue by netyaroze** [regolith-linux/website#143]
In the following document:
https://regolith-linux.org/docs/howtos/configure-wallpaper/

The command:
`echo "gnome.wallpaper: /usr/share/backgrounds/warty-final-ubuntu.png" > ~/.config/regolith/Xresources`

Uses > instead of >> - which is safer, given we can safely guess people will be copy-pasting sometimes. Anyone doing so will overwrite the config file if values are already configured in the file.

**Comment by nsunderland1** [comment]
Agreed with this. I actually ran into this today. Glanced over the command quickly, didn't stop to think that it was `>` instead of `>>`, and overwrote my `Xresources`. Luckily I only had a couple of things set in there, but it could've been a lot worse.

**Comment by kgilmer** [comment]
Thanks, sorry it took me so long to fix this!
