### ISSUE TITLE
regolith-linux.org redirects to regolith-dekstop.com

### ISSUE THREAD

**Issue by drasbeck** [regolith-linux/website#173]
I am experiencing that any attempt of accessing regolith-linux.org or sub pages result in a redirect to regolith-desktop.com.

Is this on purpose?

**Comment by kgilmer** [comment]
Hi @drasbeck , yes this was intentional to draw attention to the new release.  You can access the older 1.x site at this URL: https://regolith-linux.github.io/regolith-site-r16/
