### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by priestoferis** [regolith-linux/website#21]
> To change the default super binding from the windows key to alt, add the following line to the file ~/.config/regolith/Xresources:

Shouldn't this be `~/.Xresources-regolith`?

**Comment by moritzheiber** [comment]
No, the correct file is `~/.config/regolith/Xresources`

**Comment by priestoferis** [comment]
That file was not created for me, should it have been? If not, maybe it would be a good idea to indicated that you need to create it. Also I think the "here" in the previous sentence is missing a link.

**Comment by moritzheiber** [comment]
The file is not created, as the setup works without it. Maybe submit your suggestions in a PR?

**Comment by cheginit** [comment]
This is the new approach probably since version 1.4, if I remember correctly.

**Comment by kgilmer** [comment]
IMHO the wording doesn't necessarily imply that the file should already exist.  I wasn't able to reword the paragraph such that the base case and the non-assumption of existence are both simply expressed.  Any suggestions?

Here is the reference page for config files: https://regolith-linux.org/docs/reference/configurations/

**Comment by kgilmer** [comment]
Closing due to staleness.  Feel free to reopen if remaining action desired.
