### ISSUE TITLE
docs: Stage Config Files

### ISSUE THREAD

**Issue by pektinasen** [regolith-linux/website#39]
re: https://regolith-linux.org/docs/howto/stage-configs/

I think the condition in the highlighted box should go first, to make it clear it's only for Xresource. when reading quickly one might get confused if staging configs is still necessary or not. (unless I'm reading it wrong and staging configs is no longer necessary)

Regolith 1.3.1 and above:
If you only wish to override or provide new Xresource values, staging configs is no longer required. See this page for more details.

**Comment by kgilmer** [comment]
Thanks @pektinasen , fixed in the above commit.
