### ISSUE TITLE
Add instructions for using vanilla i3gaps 

### ISSUE THREAD

**Issue by renxida** [regolith-linux/website#52]
https://gist.github.com/renxida/7f594c13261c2aaac0de31f06bd41427

I made a gist. Couldn't test it because hugo server reports a scss error possibly related to an outdated theme. Could someone add this to `/content/en/docs/HowTo/`, test it, and get a pull request in?

**Comment by kgilmer** [comment]
Hi Xida, I've done as you've requested: https://github.com/regolith-linux/website/commit/95891bb87c97c8f041e3ad10ad98667ade431411

Thanks for your contribution!  I noticed on your bio that you're from China.  If you're interested in contributing more we'd love to have a Chinese translation of the [landing page](https://github.com/regolith-linux/website/blob/master/content/en/_index.md).
