### ISSUE TITLE
Setup local

### ISSUE THREAD

**Issue by murilooon** [regolith-linux/website#71]
Hi,

I'm trying to setup the website locally but i'm getting the following error:

![image](https://user-images.githubusercontent.com/16845851/105364938-7e032480-5bdc-11eb-8fa4-aa52215d2fac.png)

Could you guys tell me what's the `node` and `npm` version that I should use?

PS: I want to contribute translating the documentation to `pt-br`.

**Comment by moritzheiber** [comment]
Hey, I don't know exactly what's wrong with it but we're currently working on modifying the website to work with Crowdin for translations, It'll be easier to contribute then. I'll probably get it out the door this weekend, I would ask you to hold on with contributing translations just a little while longer until then :) Thanks!

**Comment by moritzheiber** [comment]
(I'll drop in here again once it's done to let you know about the process!)

**Comment by murilooon** [comment]
Oh, awesome. I love Crowdin, it will be really easier. Thank you!!!

**Comment by moritzheiber** [comment]
@murilooon If you want to be one of our beta handlers, you can get started now here: https://regolith-linux.crowdin.com/regolith-linux

**Comment by murilooon** [comment]
Alright, I will translate some text to test :rocket:

**Comment by murilooon** [comment]
Just to know, I'm talking to some friends to help translating to Brazilian Portuguese. They love Regolith too :heart: Actually, they showed me this beauty

**Comment by murilooon** [comment]
Hey @moritzheiber. I'm receiving 404 when trying to access https://regolith-linux.crowdin.com/regolith-linux. Something happened?

**Comment by moritzheiber** [comment]
@murilooon Yup, sorry, I had to completely remove the project and start from scratch, as the translations Crowdin fed back into the repository were corrupt. I'll let you know once we can start this effort up again. My apologies for, potentially, wasted effort, but I did say it was going to be "beta" :wink:

**Comment by murilooon** [comment]
Oh, no problem, I will wait until I can translate without problem, don't worry about it. :smile:

**Comment by kgilmer** [comment]
@murilooon hello :)  It's been awhile but FYI the crowdin integration that @moritzheiber added is ready to be used.  You can create an account from here: https://regolith-linux.crowdin.com/

Please LMK if you try this but it doesn't work, I'm new to this service.

**Comment by murilooon** [comment]
Hey, now the regolith crowdin link worked, thanks! :tada:
